name: Maplands
main: com.bergerkiller.bukkit.maplands.Maplands
api-version: 1.13
version: ${project.version}
authors: [bergerkiller]
description: Minecraft worlds in the map dimension
depend: [BKCommonLib]
metrics: true
dev-url: ${project.url}
commands:
    maplands:
        aliases: [map]
        description: Gives access to the maplands map item
        usage: /map or /map give [playername]
